# Generated by Django 2.2.4 on 2020-06-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agent', models.ManyToManyField(related_name='personas', related_query_name='persona', to='agent_api.Agent')),
            ],
        ),
    ]
