# Generated by Django 2.2.4 on 2020-06-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0002_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
